name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker steps
      - name: Docker Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: . # Path to Dockerfile context
          file: ./Dockerfile # Path to Dockerfile
          platforms: linux/amd64 # Specify platforms if needed, e.g., linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
          # Consider adding cache-from and cache-to for Docker layer caching if appropriate
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Image digest
        if: steps.docker_build.outputs.digest
        run: |
          echo "Digest: ${{ steps.docker_build.outputs.digest }}"
          echo "Image pushed successfully!"

      - name: Final Disk Space Check
        run: df -h